name: AntiPVPLog
main: com.Melvin3000.AntiPVPLog.AntiPVPLog
version: 0.1
api-version: 1.16
commands:
    logout:
        description: Safe logout from server
        usage: /<command>
softdepend: [Jail]